### ISSUE TITLE
Don't work with MorphWebBrowser

### ISSUE THREAD

**Issue by tux4us** [florisluiten/rssreader#11]
The rss-reader  doesn't making feed updates and the "read more" webview is empty. The link to the browser is dead.
UbuntuTouch 16.04 dev and rc

**Comment by balcy** [comment]
the second problem is solved by https://github.com/ubports/morph-browser/pull/75
the first requires 
https://github.com/ubports/morph-browser/pull/76 and the use of the new parameter in the desktop file

**Comment by balcy** [comment]
https://github.com/florisluiten/rssreader/pull/12
works with the current dev / RC of morph (or with OTA-6)

**Comment by florisluiten** [comment]
Hi balcy and tux4us,

Thank you guys for the issue and PR. I'll be looking into this soon (I hope)

**Comment by florisluiten** [comment]
Hi guys,

I've published version 0.3.0 to the OpenStore, which should fix this issue. Can you please update to this version? 

Thanks again,

Floris

**Comment by tux4us** [comment]
It works. Thank you for your work.
