### ISSUE TITLE
scrolling on main page is not working

### ISSUE THREAD

**Issue by fabianHAW** [florisluiten/rssreader#9]
if i have more than 14 feeds in the reader, i have to scroll down and up. but it seems it is not working for me. nothing happens when i try to scroll. if i click on a feed and there are more than 14 articles, the scrolling is working..

ubuntu: 15.04 r3
rssreader: 0.2.4

**Comment by mublinas** [comment]
IT seemed that i had the same problem, but when i tried with two fingers IT worked for me. Perhaps you can let me know if this is in your case?

**Comment by fabianHAW** [comment]
wow it works! never thought about it..thanks a lot :)
